### ISSUE TITLE
Add restriction that usable prefix must be /64; reference RFC 7084 section 4.3 requirement L-2.

### ISSUE THREAD

**Issue by Abhayakara** [ietf-wg-snac/draft-ietf-snac-simple#30]
This is based on Alan Collins' review of the document here:

https://mailarchive.ietf.org/arch/msg/snac/0wzbsMx_1uHFHEdw-cftEufoi-k

**Comment by EskoDijk** [comment]
RFC 7084 is Informational only; so that alone may not make the reason for the requirement fully clear.
In RFC 4862 (Standards track) Section 5.5.3 the reason becomes clear:

      If the sum of the prefix length and interface identifier length
      does not equal 128 bits, the Prefix Information option MUST be
      ignored.  

So that shows why any PIO other than /64 on the Wi-Fi or Ethernet link is not usable: because a host won't use it for SLAAC.
