### ISSUE TITLE
What icmpv6 RA behavior to expect when same device is both ipv6 Router and Stub Router ?

### ISSUE THREAD

**Issue by alan-eero** [ietf-wg-snac/draft-ietf-snac-simple#62]
example: device is home gateway that allows user to enable/disable ipv6 upstream (ipv6 router), and to enable/disable device Thread border router (stub router). 

This scenario leads to the same device sending two RAs with different options content, but same link-local source address. Example:  first RA contains PIO and RDNSS. Second RA contains RIO only. 
 
This should not affect options like PIO nor RIO, because hosts should use the lifetime to deprecate the usage, but some implementations consuming RDNSS will find the second RA as an statement that recursive DNS server is no longer available so hosts using that implementation will stop using it. I believe this is a gap in that RDNSS implementation driven by the ambiguity of   https://www.rfc-editor.org/rfc/rfc6106#section-5.3.1 - however, what will be the action or expectation from SNAC to workaround / prevent these misinterpretations.

**Comment by alan-eero** [comment]
FYI: @EskoDijk , @Abhayakara

**Comment by Abhayakara** [comment]
This is not really a SNAC use case: the device you've described is a CE router with three interfaces, not a stub router. The three interfaces are:

- WAN
- LAN
- "Stub" network

The CE router is expected to get its internet connectivity through the WAN interface. The LAN interface and the "stub network" interface are just two different southbound interfaces, which can be configured by the router. There's no reason for the router to do any negotiation—it's the home network router. It should just publish a prefix on each link, advertise RAs on each link (assuming RAs are supported on the stub link; if not, e.g. on Thread, do what that link requires that's equivalent). 

The reason we do things so dynamically with stub networks is that there is no source of authority, but that's not really the case for a CE router. I guess if you have two CE routers both of which have a connection to infrastructure and to the stub network, you might want to find a way for them to co-operate, particularly on a constrained network like Thread.

In that case, it might make sense to implement the stub network behavior described here. The behavior on the LAN would be dictated by RFC7084, though, not by any SNAC document.

Sending two RAs seems like it would just be wrong behavior, and certainly we shouldn't explain how to do this or encourage it. If it isn't out of scope for this document, I think we should explicitly forbid it.

**Comment by EskoDijk** [comment]
The current SNAC-simple draft includes in its scope a Home Gateway that includes a stub-router function. (New name for this function is SNAC router per #57). In fact all of the interoperability + usability goals still hold for this configuration. 

But since the SNAC router function assumes some other entity, called Home Gateway, forms the home network (see Section 2 glossary) and provides services, we will probably need some more scoping and clarifications for this case of a combined device. This is what I created #61 for.  For example to clarify how RAs can be sent (both multicast / unicast).

For the home gateway / CPE router / CE router example that is sending two separate RAs on the LAN from the same link-local source address: per the IETF specs this would work ok for multicast RAs, it seems.  However if the home gateway would decide to use unicast RA to respond to an RS, that seems problematic -- sending two unicast RAs in response to an RS is not covered by the ND protocol in my opinion.  Maybe sending one unicast RA followed by one  multicast RA would be allowed by the specs, though it could have unwanted effects for some host implementations (just guessing here).  It would be more straighforward if the home gateway would just combine all the information in one RA. So we might narrow the scope of the draft to this case only?  The single RA can then be adapted based on whether the IPv6 router function is on/off, and the SNAC router function is on/off. (3 cases in total)

One further case is where a home gateway like this has its WAN port unconnected and gets added to an existing LAN (governed by another CE router). By default, it has its SNAC router function enabled so it will have to implement the SNAC router requirements: for example provide ULA PIO on LAN in case the CE router isn't sending a "suitable" prefix.
This case seems definitely within scope of SNAC.

**Comment by Abhayakara** [comment]
In the case that the stub router is connected to a stub network that is provisioned by an RFC7084 router, I think the stub router should not be advertising routers to the stub network.

**Comment by EskoDijk** [comment]
> stub network that is provisioned by an RFC7084 router, I think the stub router should not be advertising routers to the stub network

You mean a SNAC router that gets connected to the stub network of a RFC7084 / CE router (which is not a SNAC router as we agreed) ?  What happens then would depend on which interface of the new SNAC router gets connected to the stub network.
Possible cases for example:
1. SNAC router with 6lowpan mesh (e.g. Thread or 6tisch) as stub network interface - Wi-Fi as AIL interface
2. SNAC router with 6lowpan mesh (e.g. Thread or 6tisch) as stub network interface - Ethernet as AIL interface
3. SNAC router with Wi-Fi as stub network interface - Ethernet as AIL interface

If the stub network provisioned by the CE router is 6lowpan mesh, then a SNAC router that gets attached to it will always treat the stub network as a "stub network" and it will not send RAs or equivalent to it that are intended for the AIL side.
However if the stub network provisioned by the CE router is  Wi-Fi, then a type 1 SNAC router attached to it will treat the WiFi as an AIL and send RAs to it with RIO and possibly also PIO.

What seems to happen then is that the intended "stub network" provisioned by the CE router is not a stub anymore, since the SNAC router uses it for transit traffic. Can the network be stub and not-stub at the same time? (this has some quantum vibe to it)

**Comment by Abhayakara** [comment]
I think in the case of the WiFi network, the CE router is not explicitly considering it a stub network and it is certainly not a SNAC network. So it seems fine for the SNAC router to treat it as an infrastructure network—in fact, I think it would be incorrect for it to not do so.

**Comment by EskoDijk** [comment]
The current text in the draft that could be incorrect is the following (second sentence "exception ..." ):

> A SNAC router SHOULD NOT advertise itself as a default router on an AIL by setting a non-zero Router Lifetime value in the header of its Router Advertisements. The exception to this rule is the case where the SNAC router itself is the default router for a particular AIL: for example, it may be the home router providing connectivity to an ISP.

And the below:

> If the SNAC router is also a normal router (e.g. a home WiFi router), it SHOULD include all other routes that it is advertising in the RA, if there is space
